## Decision Tree for classification:- By ID3 algoritham

### Variables:-
#dummy_df = Dummy dataframe
#m = Male
#f = Female
#A = Grade- A
#B = Grade- B
#I_G_ = Information Gain

In [2]:
import pandas as pd
import numpy as np

In [133]:
dummy_df = pd.DataFrame({'Gender':['m','f','m','m','m','f'], 'Marks':[23,23,18,13.5,11.2,19.92],
                   'Result': ['A','A','A','B','A','B']})
dummy_df

Gender  Marks Result
0      m  23.00      A
1      f  23.00      A
2      m  18.00      A
3      m  13.50      B
4      m  11.20      A
5      f  19.92      B

#### Step(1)
Entropy of target(dummy_df['Result']):- sigma(-p log2 p)

In [151]:
def Entropy(p,q):
    prob_p = p/(p+q)
    prob_q = q/(p+q)
    return(-prob_p*np.log2(np.array([prob_p])) -prob_q*np.log2(np.array([prob_q])))

In [164]:
A = dummy_df[dummy_df['Result'] == 'A']['Result'].shape[0]
B = dummy_df[dummy_df['Result'] == 'B']['Result'].shape[0]
Entropy_Target = Entropy(A,B)
Entropy_Target

array([0.91829583])

#### Step(2)
#Find entropy of every feature:- sigma(P(c)*E(c))
#P(c) = Probability of c
#E(c) = Entropy of c

In [153]:
def Entropy_feature(m,m_a,m_b,f,f_a,f_b):
    prob_entropy_m = m/(m+f) * Entropy(m_a,m_b)
    prob_entropy_f = f/(m+f) * Entropy(f_a,f_b)
    return(prob_entropy_m + prob_entropy_f)

In [154]:
m = dummy_df[dummy_df['Gender'] == 'm'].shape[0]
m_a = dummy_df[(dummy_df['Gender'] == 'm') & (dummy_df['Result'] == 'A')].shape[0]
m_b = dummy_df[(dummy_df['Gender'] == 'm') & (dummy_df['Result'] == 'B')].shape[0]

f = dummy_df[dummy_df['Gender'] == 'f'].shape[0]
f_a = dummy_df[(dummy_df['Gender'] == 'f') & (dummy_df['Result'] == 'A')].shape[0] 
f_b = dummy_df[(dummy_df['Gender'] == 'f') & (dummy_df['Result'] == 'A')].shape[0] 

Entropy_Gender = Entropy_feature(m,m_a,m_b,f,f_a,f_b)
Entropy_Gender

array([0.87418542])

#### Use bining method for find entropy of the continuous data points

In [138]:
dummy_df.loc[dummy_df[(dummy_df['Marks']>=10) & (dummy_df['Marks']<15)].index, 'Marks'] = 1
dummy_df.loc[dummy_df[(dummy_df['Marks']>=15) & (dummy_df['Marks']<20)].index, 'Marks'] = 2
dummy_df.loc[dummy_df[(dummy_df['Marks']>=20)].index, 'Marks'] = 3

In [155]:
def Entropy_feature(M_1, M_1_a, M_1_b, M_2, M_2_a, M_2_b, M_3, M_3_a, M_3_b):
    prob_entropy_M_1 = M_1/(M_1+M_2+M_3) * Entropy(M_1_a, M_1_b)
    prob_entropy_M_2 = M_2/(M_1+M_2+M_3) * Entropy(M_2_a, M_2_b)
    prob_entropy_M_3 = M_3/(M_1+M_2+M_3) * np.array([0])
    return(prob_entropy_M_1 + prob_entropy_M_2 + prob_entropy_M_3)

In [156]:
M_1 = dummy_df[dummy_df['Marks'] == 1].shape[0]
M_1_a = dummy_df[(dummy_df['Marks'] == 1) & (dummy_df['Result'] == 'A')].shape[0]
M_1_b = dummy_df[(dummy_df['Marks'] == 1) & (dummy_df['Result'] == 'B')].shape[0]

M_2 = dummy_df[dummy_df['Marks'] == 2].shape[0]
M_2_a = dummy_df[(dummy_df['Marks'] == 2) & (dummy_df['Result'] == 'A')].shape[0] 
M_2_b = dummy_df[(dummy_df['Marks'] == 2) & (dummy_df['Result'] == 'A')].shape[0] 

M_3 = dummy_df[dummy_df['Marks'] == 3].shape[0]
M_3_a = dummy_df[(dummy_df['Marks'] == 3) & (dummy_df['Result'] == 'A')].shape[0]
M_3_b = dummy_df[(dummy_df['Marks'] == 3) & (dummy_df['Result'] == 'B')].shape[0]

Entropy_Marks = Entropy_feature(M_1, M_1_a, M_1_b, M_2, M_2_a, M_2_b, M_3, M_3_a, M_3_b)
Entropy_Marks

array([0.66666667])

#### Step(3) Find inforamtion Gain
Entropy before split - Entropy after split

In [163]:
###  For Gender
I_G_Gender = Entropy_Target - Entropy_Gender
I_G_Marks = Entropy_Target - Entropy_Marks
print('I_G_Gender:- ',I_G_Gender)
print('I_G_Marks:-',I_G_Marks)

I_G_Gender:-  [0.04411042]
I_G_Marks:- [0.25162917]


### So I_G_Marks is greater so choose it as spliter and for next spliter we repeat this method for rest data at every node